In [1]:
!pip install pandas

In [2]:
!pip install -U scikit-learn


In [3]:
!pip install numpy

In [4]:
import pandas as pd
import numpy as np
from sklearn import datasets


In [5]:
serl = pd.Series([1,2,3,4], index=['A','B','C','D'])

In [6]:
serl

A    1
B    2
C    3
D    4
dtype: int64

In [7]:
serl['C']

3

In [8]:
dictionary1 = {'ID':[1,1,1,2,2,2,3,3,3],'Score':[1,2,3,4,5,6,7,8,9]}

In [9]:
dictionary1

{'ID': [1, 1, 1, 2, 2, 2, 3, 3, 3], 'Score': [1, 2, 3, 4, 5, 6, 7, 8, 9]}

#

In [10]:
df1 = pd.DataFrame(dictionary1)

In [11]:
df1

ID  Score
0   1      1
1   1      2
2   1      3
3   2      4
4   2      5
5   2      6
6   3      7
7   3      8
8   3      9

In [12]:
df1.groupby(['ID']).mean()

Score
ID       
1     2.0
2     5.0
3     8.0

In [13]:
df2=df1.groupby(['ID']).mean().reset_index()

In [14]:
df3 = pd.concat([df1,df2])

In [15]:
df3

ID  Score
0   1    1.0
1   1    2.0
2   1    3.0
3   2    4.0
4   2    5.0
5   2    6.0
6   3    7.0
7   3    8.0
8   3    9.0
0   1    2.0
1   2    5.0
2   3    8.0

In [16]:
df2

ID  Score
0   1    2.0
1   2    5.0
2   3    8.0

In [17]:
df2.columns = ['ID','Math']

In [18]:
df2

ID  Math
0   1   2.0
1   2   5.0
2   3   8.0

In [19]:
diction4 = {'ID':[2,4,5],'Physics':[4,5,6]}
df4 = pd.DataFrame(diction4)
df4

ID  Physics
0   2        4
1   4        5
2   5        6

In [20]:
df_left_join = pd.merge(df2,df4,how='left',on='ID')
df_left_join

ID  Math  Physics
0   1   2.0      NaN
1   2   5.0      4.0
2   3   8.0      NaN

In [21]:
df_inner_join = pd.merge(df2,df4,how='inner',on='ID')
df_inner_join

ID  Math  Physics
0   2   5.0        4

In [22]:
df_right_join = pd.merge(df2,df4,how='right',on='ID')
df_right_join

ID  Math  Physics
0   2   5.0        4
1   4   NaN        5
2   5   NaN        6

In [23]:
from sklearn import datasets

In [24]:
iris = datasets.load_iris()

In [25]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [26]:
iris_array = iris['data']
iris_array 

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [27]:
iris_label = iris['target']
iris_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [28]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [29]:
scaler=  StandardScaler()

In [30]:
new_data = scaler.fit(iris_array)

In [31]:
new_data

StandardScaler()

In [32]:
print(scaler.mean_)

[5.84333333 3.05733333 3.758      1.19933333]


In [33]:
print(scaler.transform(iris_array))

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

In [34]:
new_data2 = scaler.transform(iris_array)

In [35]:
np.mean(new_data2,axis = 0)

array([-1.69031455e-15, -1.84297022e-15, -1.69864123e-15, -1.40924309e-15])

In [36]:
np.mean(iris_array,axis = 0)

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [37]:
np.mean(iris_array,axis = 0)

array([5.84333333, 3.05733333, 3.758     , 1.19933333])